### ISSUE TITLE
Ottersync has been stuck for 6 hours.

### ISSUE THREAD

**Issue by B1Q** [erigontech/erigon#14934]
I am on the latest version of erigon 3 (fresh pull yesterday) 
Node has been stuck downloading for 6 hours now. 

the following message pops up every 20-30 seconds:

INFO[05-08|04:00:32.898] [1/6 OtterSync] Downloading              progress="(709/709 files) 75.55% - 738.8GB/977.8GB" time-left=999hrs:99m total-time=12h24m20s download-rate=0B/s completion-rate=0B/s alloc=911.6MB sys=6.5GB

Download rate is 0B/s and nothing else is happening except a bunch of "Unsupported fork" warnings.

**Comment by mwmouawad** [comment]
Same here! On version 3.0.3

**Comment by Sleapy31** [comment]
Same here! On version 3.0.3 and 3.0.2.

**Comment by B1Q** [comment]
seems to be completely DEAD. Going back to 2.61 
I tried to sync on 3 servers and all i'm getting is 0B/s and it downloaded 200kb after 3 hours.

**Comment by hitdavid** [comment]
> seems to be completely DEAD. Going back to 2.61 I tried to sync on 3 servers and all i'm getting is 0B/s and it downloaded 200kb after 3 hours.

my v2.61.3 instance is dead, see https://github.com/erigontech/erigon/issues/14933

**Comment by sstonehu** [comment]
I can't download when using v3.0.3....

[INFO] [05-08|06:14:46.589] [1/6 OtterSync] Downloading              progress="(0/1 files) 0.00% - 0B/0B" time-left=999hrs:99m total-time=20s download-rate=0B/s completion-rate=0B/s alloc=2.0GB sys=2.1GB
[INFO] [05-08|06:14:46.589] [snapshots] no metadata yet              files=1 list=salt-blocks.txt
[INFO] [05-08|06:15:06.589] [1/6 OtterSync] Downloading              progress="(0/1 files) 0.00% - 0B/0B" time-left=999hrs:99m total-time=40s download-rate=0B/s completion-rate=0B/s alloc=2.0GB sys=2.1GB
[INFO] [05-08|06:15:06.590] [snapshots] no metadata yet              files=1 list=salt-blocks.txt
[INFO] [05-08|06:15:26.589] [1/6 OtterSync] Downloading              progress="(0/1 files) 0.00% - 0B/0B" time-left=999hrs:99m total-time=1m0s download-rate=0B/s completion-rate=0B/s alloc=2.0GB sys=2.1GB
[INFO] [05-08|06:15:26.589] [snapshots] no metadata yet              files=1 list=salt-blocks.txt
[INFO] [05-08|06:15:32.762] P2P                                      app=caplin peers=2
[INFO] [05-08|06:15:46.589] [1/6 OtterSync] Downloading              progress="(0/1 files) 0.00% - 0B/0B" time-left=999hrs:99m total-time=1m20s download-rate=0B/s completion-rate=0B/s alloc=1.4GB sys=2.2GB
[EROR] [05-08|06:15:46.630] Could not start execution service        err="[1/6 OtterSync] strconv.ParseUint: parsing \"accounts\": invalid syntax"
[INFO] [05-08|06:16:06.589] [1/6 OtterSync] Downloading complete     time=1m39.967808502s

**Comment by B1Q** [comment]
> > seems to be completely DEAD. Going back to 2.61 I tried to sync on 3 servers and all i'm getting is 0B/s and it downloaded 200kb after 3 hours.
> 
> my v2.61.3 instance is dead, see [#14933](https://github.com/erigontech/erigon/issues/14933)

fucking hell

**Comment by mwmouawad** [comment]
I have tried 3.0.3 and 3.0.0. I went to Erigon 3 because I was having problems with Erigon 2.6.1 sync. Now my archive sync is

` INFO[05-08|09:34:20.341] [1/6 OtterSync] Downloading              progress="(1453/1453 files) 46.24% - 864.3GB/1.8TB" time-left=999hrs:99m total-time=43m20s download-rate=0B/s completion-rate=0B/s alloc=12.5GB sys=15.2GB`

with

`INFO[05-08|09:33:08.805] P2P       app=caplin peers=127
`

since yesterday. I have restarted the sync multiple times, changed multiple options and still stuck.

**Comment by B1Q** [comment]
> I have tried 3.0.3 and 3.0.0. I went to Erigon 3 because I was having problems with Erigon 2.6.1 sync. Now my archive sync is
> 
> ` INFO[05-08|09:34:20.341] [1/6 OtterSync] Downloading progress="(1453/1453 files) 46.24% - 864.3GB/1.8TB" time-left=999hrs:99m total-time=43m20s download-rate=0B/s completion-rate=0B/s alloc=12.5GB sys=15.2GB`
> 
> with
> 
> `INFO[05-08|09:33:08.805] P2P app=caplin peers=127 `
> 
> since yesterday. I have restarted the sync multiple times, changed multiple options and still stuck.

Yeah I couldn't get anything to download properly, not 2.61 or 3.0.3. back to geth

**Comment by popalot2** [comment]
I think something is broken in the torrent client, downloading the torrents manually with aria2c works fine but the downloader is stuck.
Maybe it has something to do with the load on the default webseed, it seems to be hammered and returning a lot of errors.




```

DBUG[05-08|06:52:03.084] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-011000-011500-transactions.seg": requests 0 (p=0,d=47518,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(17/5957) lastUpdate=9.685953719s
DBUG[05-08|06:52:03.085] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-020800-020900-transactions.seg": requester 81: error doing webseed request &{1413 {786432 262144}}: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-020800-020900-transactions.seg" at "bytes=2964062208-2964324351": unhandled response status code (403)
DBUG[05-08|06:52:03.143] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-013500-014000-transactions.idx": requests 0 (p=0,d=1975,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(60/307) lastUpdate=9.524719284s
DBUG[05-08|06:52:03.177] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-013500-014000-transactions-to-block.idx": requests 0 (p=0,d=801,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(54/155) lastUpdate=9.688314661s
DBUG[05-08|06:52:03.372] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx": Request {205 {1310720 262144}} rejected: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx" at "bytes=431226880-431489023": unhandled response status code (403)
DBUG[05-08|06:52:03.374] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx": requester 116: error doing webseed request &{205 {1310720 262144}}: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx" at "bytes=431226880-431489023": unhandled response status code (403)
DBUG[05-08|06:52:03.430] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-011500-012000-transactions.seg": requests 0 (p=0,d=54726,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(3/6844) lastUpdate=9.613513058s
DBUG[05-08|06:52:03.477] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-014000-014500-transactions-to-block.idx": requests 0 (p=0,d=952,n=141) active(c=0,r=0,p=0,m=125,w=125) hashing(q=0,a=0,h=0,r=0) complete(22/141) lastUpdate=9.824394402s
DBUG[05-08|06:52:03.586] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-014000-014500-transactions.idx": requests 0 (p=0,d=2250,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(0/282) lastUpdate=9.45088693s
DBUG[05-08|06:52:03.712] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-016500-017000-transactions.seg": Request {10685 {1835008 262144}} rejected: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-016500-017000-transactions.seg" at "bytes=22409904128-22410166271": unhandled response status code (403)
DBUG[05-08|06:52:03.759] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-014500-015000-transactions-to-block.idx": requests 0 (p=0,d=992,n=140) active(c=0,r=0,p=0,m=124,w=124) hashing(q=0,a=0,h=0,r=0) complete(16/140) lastUpdate=9.369690887s
DBUG[05-08|06:52:03.759] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-012000-012500-transactions.seg": requests 0 (p=0,d=60576,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(18/7590) lastUpdate=9.500439659s
DBUG[05-08|06:52:03.781] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-013000-013500-transactions.seg": requests 0 (p=0,d=70571,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(46/8868) lastUpdate=8.779831758s

```

**Comment by B1Q** [comment]
> I think something is broken in the torrent client, downloading the torrents manually with aria2c works fine but the downloader is stuck. Maybe it has something to do with the load on the default webseed, it seems to be hammered and returning a lot of errors.
> 
> ```
> 
> DBUG[05-08|06:52:03.084] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-011000-011500-transactions.seg": requests 0 (p=0,d=47518,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(17/5957) lastUpdate=9.685953719s
> DBUG[05-08|06:52:03.085] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-020800-020900-transactions.seg": requester 81: error doing webseed request &{1413 {786432 262144}}: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-020800-020900-transactions.seg" at "bytes=2964062208-2964324351": unhandled response status code (403)
> DBUG[05-08|06:52:03.143] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-013500-014000-transactions.idx": requests 0 (p=0,d=1975,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(60/307) lastUpdate=9.524719284s
> DBUG[05-08|06:52:03.177] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-013500-014000-transactions-to-block.idx": requests 0 (p=0,d=801,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(54/155) lastUpdate=9.688314661s
> DBUG[05-08|06:52:03.372] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx": Request {205 {1310720 262144}} rejected: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx" at "bytes=431226880-431489023": unhandled response status code (403)
> DBUG[05-08|06:52:03.374] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx": requester 116: error doing webseed request &{205 {1310720 262144}}: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-004500-005000-transactions.idx" at "bytes=431226880-431489023": unhandled response status code (403)
> DBUG[05-08|06:52:03.430] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-011500-012000-transactions.seg": requests 0 (p=0,d=54726,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(3/6844) lastUpdate=9.613513058s
> DBUG[05-08|06:52:03.477] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-014000-014500-transactions-to-block.idx": requests 0 (p=0,d=952,n=141) active(c=0,r=0,p=0,m=125,w=125) hashing(q=0,a=0,h=0,r=0) complete(22/141) lastUpdate=9.824394402s
> DBUG[05-08|06:52:03.586] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-014000-014500-transactions.idx": requests 0 (p=0,d=2250,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(0/282) lastUpdate=9.45088693s
> DBUG[05-08|06:52:03.712] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-016500-017000-transactions.seg": Request {10685 {1835008 262144}} rejected: reading "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-016500-017000-transactions.seg" at "bytes=22409904128-22410166271": unhandled response status code (403)
> DBUG[05-08|06:52:03.759] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-014500-015000-transactions-to-block.idx": requests 0 (p=0,d=992,n=140) active(c=0,r=0,p=0,m=124,w=124) hashing(q=0,a=0,h=0,r=0) complete(16/140) lastUpdate=9.369690887s
> DBUG[05-08|06:52:03.759] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-012000-012500-transactions.seg": requests 0 (p=0,d=60576,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(18/7590) lastUpdate=9.500439659s
> DBUG[05-08|06:52:03.781] webseed peer for "https://erigon3-v1-snapshots-mainnet.erigon.network/v1-013000-013500-transactions.seg": requests 0 (p=0,d=70571,n=150) active(c=0,r=0,p=0,m=134,w=134) hashing(q=0,a=0,h=0,r=0) complete(46/8868) lastUpdate=8.779831758s
> ```

what's the solution to this issue?

**Comment by popalot2** [comment]
> > I think something is broken in the torrent client, downloading the torrents manually with aria2c works fine but the downloader is stuck. Maybe it has something to do with the load on the default webseed, it seems to be hammered and returning a lot of errors.
 
> what's the solution to this issue?

I am not sure, I switched nethermind because of this on one server.
Trying to also run the download manually using aria2c but I am not sure yet how to have erigon pickup the files downloaded by aria2c

**Comment by B1Q** [comment]
> > > I think something is broken in the torrent client, downloading the torrents manually with aria2c works fine but the downloader is stuck. Maybe it has something to do with the load on the default webseed, it seems to be hammered and returning a lot of errors.
> 
> > what's the solution to this issue?
> 
> I am not sure, I switched to nethermind because of this on one server. Trying to also run the download manually using aria2c but I am not sure yet how to have erigon pickup the files downloaded by aria2c

yeah, I did the same. 

Anyone having this issue just switch to nethermind or geth. I will check back in a few months maybe erigon will be stable by then

**Comment by VBulikov** [comment]
yperbasis added Imp1 as Importance

**Comment by awskii** [comment]
@popalot2 yes Erigon will be fine grabbing files downloaded using same torrents via any torrent client.

**Comment by VBulikov** [comment]
yperbasis changed Importance from Imp1 to Imp0

**Comment by awskii** [comment]
so as in place solution you can use recent main instead of v3.0.3. Yes it is experimental but downloading working just fine there
@popalot2 @B1Q @hitdavid 

2.61 does not support Pectra which get live yestarday and there was public announcement about upcoming change and required transition.

**Comment by popalot2** [comment]
> so as in place solution you can use `699b6a4bf717f627f7850cee2dd5b7c908d855c9` instead of v3.0.3. Yes it is experimental but downloading working just fine there

I don't see any difference in behavior with 699b6a4bf717f627f7850cee2dd5b7c908d855c9

**Comment by Sleapy31** [comment]
> so as in place solution you can use `699b6a4bf717f627f7850cee2dd5b7c908d855c9` instead of v3.0.3. Yes it is experimental but downloading working just fine there [@popalot2](https://github.com/popalot2) [@B1Q](https://github.com/B1Q) [@hitdavid](https://github.com/hitdavid)
> 
> 2.61 does not support Pectra which get live yestarday and there was public announcement about upcoming change and required transition.

Hi, I am using main branch and it is working as intended thank you. I have more than 100MB/s now.

**Comment by lystopad** [comment]
Please, try now. The issue should be solved since 1h.
Thanks for the report @B1Q and others.

**Comment by mwmouawad** [comment]
@lystopad Thank you!  Sync its working now. I am having again 100mb/s with 127 peers.

**Comment by popalot2** [comment]
I personally don't see any difference with 699b6a4bf717f627f7850cee2dd5b7c908d855c9 
It started downloading at about 2-7MB per second and came to a complete halt.
Most of the 942.1GB was downloaded with aria2c.

@awskii also every time I start erigon now, it rescans the snapshot files (I guess to verify the signatures) but it takes a long time and io, I home when the download completes it will note somewhere that the files are good and wouldn't run for 20 minutes verifying files every time.

`[INFO] [05-09|05:57:43.073] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h38m32s download-rate=0B/s comp
letion-rate=0B/s alloc=5.4GB sys=8.0GB
[INFO] [05-09|05:57:43.724] P2P                                      app=caplin peers=110
[INFO] [05-09|05:58:03.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h38m52s download-rate=0B/s comp
letion-rate=0B/s alloc=6.6GB sys=8.0GB
[INFO] [05-09|05:58:03.072] [p2p] GoodPeers                          eth68=351 eth67=102
[INFO] [05-09|05:58:04.276] [mem] memory stats                       Rss=22.6GB Size=0B Pss=22.6GB SharedClean=2.3MB SharedDirty=0B PrivateClean=14.8GB PrivateDirty=7.8GB Referenced=22.
6GB Anonymous=7.8GB Swap=0B alloc=6.7GB sys=8.0GB
[INFO] [05-09|05:58:10.591] [txpool] stat                            pending=0 baseFee=0 queued=0
[INFO] [05-09|05:58:23.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h39m12s download-rate=0B/s comp
letion-rate=0B/s alloc=3.8GB sys=8.0GB
[INFO] [05-09|05:58:43.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h39m32s download-rate=0B/s comp
letion-rate=0B/s alloc=4.9GB sys=8.0GB
[INFO] [05-09|05:58:43.724] P2P                                      app=caplin peers=114
[INFO] [05-09|05:59:03.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h39m52s download-rate=0B/s comp
letion-rate=0B/s alloc=5.9GB sys=8.0GB
[INFO] [05-09|05:59:23.073] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h40m12s download-rate=0B/s comp
letion-rate=0B/s alloc=7.1GB sys=8.0GB
[INFO] [05-09|05:59:33.072] [p2p] GoodPeers                          eth68=353 eth67=102
[INFO] [05-09|05:59:43.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h40m32s download-rate=0B/s comp
letion-rate=0B/s alloc=4.3GB sys=8.0GB
[INFO] [05-09|05:59:43.724] P2P                                      app=caplin peers=111
[INFO] [05-09|06:00:03.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h40m52s download-rate=0B/s comp
letion-rate=0B/s alloc=5.4GB sys=8.0GB
[INFO] [05-09|06:00:23.072] [1/6 OtterSync] Downloading              progress="(353/353 files) 94.82% - 942.1GB/993.6GB" time-left=999hrs:99m total-time=6h41m12s download-rate=0B/s comp
letion-rate=0B/s alloc=6.3GB sys=8.0GB
`

**Comment by popalot2** [comment]
@yperbasis 
Nice that you closed the ticket.
Could you explain what was/is the issue and what was changed?
For me it still doesn't work correctly.
It seems the handling of torrents in erigon is bugged as it stalls/works slower if compared to another torrent client like aria2c on the same machine and on the same torrents.

**Comment by yperbasis** [comment]
@popalot2 There's a follow-up Issue #14365

**Comment by B1Q** [comment]
> Please, try now. The issue should be solved since 1h. Thanks for the report [@B1Q](https://github.com/B1Q) and others.

Latest commit on main solved the issue yesterday.
