### ISSUE TITLE
`eth_getBlockByNumber` and `eth_getLogs` race condition

### ISSUE THREAD

**Issue by squadgazzz** [erigontech/erigon#17624]
#### System information

Erigon version: v3.0.15

OS & Version: Linux

Erigon Command (with flags/config):
```
[
      `--datadir=${dataDir}`,
      `--chain=gnosis`,
      "--http",
      "--http.addr=0.0.0.0",
      `--http.port=${clientPorts.http.containerPort}`,
      "--http.vhosts=*",
      "--http.corsdomain=*",
      "--http.api=eth,debug,net,trace,web3,erigon,txpool",
      "--ws",
      "--metrics",
      "--metrics.addr=0.0.0.0",
      `--metrics.port=${clientPorts.metrics.containerPort}`,
      "--private.api.addr=127.0.0.1:9001",
      "--nat=any",
      "--torrent.download.rate=1000mb",
      "--batchSize=4g",
      "--prune.mode=archive",
      "--externalcl",
      "--authrpc.addr=0.0.0.0",
      `--authrpc.port=${clientPorts.authRpc.containerPort}`,
      "--authrpc.vhosts=*",
      `--authrpc.jwtsecret=${this.jwt.jwtTokenPath}`,
]
```

Consensus Layer: Lighthouse v7.1.0

Consensus Layer Command (with flags/config):
```
[
      "lighthouse",
      "bn",
      "--network gnosis",
      "--datadir",
      mountPath,
      "--execution-jwt",
      jwt.jwtTokenPath,
      "--execution-endpoint",
      `http://127.0.0.1:${authRpcPort}`,
      "--metrics",
      "--metrics-address",
      "0.0.0.0",
      "--metrics-port",
      clientPorts.metrics.containerPort.toString(),
      "--checkpoint-sync-url",
      checkpointSyncUrl,
      "--http",
      "--http-address",
      "0.0.0.0",
]
```

Chain/Network: Gnosis

#### Expected behaviour
If a block is available via `eth_getBlockByNumber`, then `eth_getLogs` should either:
1. Wait/block until execution catches up for that block, or
2. Return an error indicating execution hasn't reached that block yet

Both methods should be consistent about block availability.

#### Actual behaviour
`eth_getBlockByNumber("latest", ...)` successfully returns block data (including hash), but `eth_getLogs` with that block hash in rare cases can return empty results. This happens probably because:

  1. `eth_getBlockByNumber("latest", ...)` resolves to the latest inserted block via `GetLatestBlockNumber()`(https://github.com/erigontech/erigon/blob/main/rpc/rpchelper/helper.go#L73-L76)
  2. `eth_getLogs` with a block hash looks up the block successfully and gets its block number (https://github.com/erigontech/erigon/blob/main/rpc/jsonrpc/eth_receipts.go#L80-L91)
  3. Then it tries to get transaction numbers via `txNumsReader.Max(tx, end)` (https://github.com/erigontech/erigon/blob/main/rpc/jsonrpc/eth_receipts.go#L186)
  4. If the block hasn't been executed yet, `MaxTxNum` returns `0, nil` (https://github.com/erigontech/erigon/blob/main/db/kv/rawdbv3/txnum.go#L196-L202)
  5. This causes the iterator to return no results, silently returning an empty logs array

#### Steps to reproduce the behaviour

It is hard to reproduce, since this is about a race condition, but:
  1. Start Erigon 3 node that's actively syncing or receiving new blocks
  2. Call `eth_getBlockByNumber("latest", false)` and get the block hash
  3. If block has been inserted but execution hasn't caught up yet, the call succeeds
  4. Immediately call `eth_getLogs` with the received block hash
  5. `eth_getLogs` returns [] instead of logs or an error

#### Backtrace
N/A

**Comment by VBulikov** [comment]
yperbasis added Imp1 as Importance

**Comment by AskAlexSharov** [comment]
commented in https://github.com/erigontech/erigon/pull/17692#pullrequestreview-3386406485 - maybe user subscribed to wrong event.

**Comment by VBulikov** [comment]
yperbasis changed Importance from Imp1 to Imp2

**Comment by yperbasis** [comment]
TODO: check what geth & nethermind do

**Comment by canepat** [comment]
IMO there are 2 different things to consider here:
- as @AskAlexSharov pointed out in https://github.com/erigontech/erigon/pull/17692#pullrequestreview-3386406485, the use case for "retrieve the logs of the latest executed block as soon as possible" is best covered using WebSockets by subscribing to the `NewHeads` event and calling `eth_getLogs` every time a new event is notified
- nevertheless, the use case `eth_getBlockByNumber` + `eth_getLogs` in polling mode is a valid one and must work flawlessly.  I'm currently trying to reproduce the issue.

**Comment by AskAlexSharov** [comment]
@canepat i guess can reproduce it in unit-tests by sleep(1min) in stage_exec.

**Comment by taratorio** [comment]
I think I have an idea when this can happen in 3.0.15:
- `eth_getBlockByNumber("latest", ...)` uses `rawdb.ReadForkchoiceHead`  to get the "latest" block
- so it is always guaranteed to be given a block that is *executed* 
- however, we had incorrect behaviour in `NewPayload` which I fixed in 3.2.2 in https://github.com/erigontech/erigon/pull/17105
- so if there was a NewPayload request from the CL to verify a side chain, it would incorrectly rollback our stage loop back to the connecting point (however it won't update the ForkChoiceHead because that can only be done by a ForkChoiceUpdate, not by a NewPayload)
-  this will unwind our block txnums index (which matches with your description)

Do you happen to have your erigon logs around the time when you saw this situation? That will help confirm the theory because we will be able to see that unfold in the logs hopefully.

Also can you try v3.2.2 and see if you hit this issue there?

**Comment by squadgazzz** [comment]
> Do you happen to have your erigon logs around the time when you saw this situation? That will help confirm the theory because we will be able to see that unfold in the logs hopefully.

Unfortunately, not atm. Next time we face it, I'll try to collect logs. Meanwhile, will try to switch to v3.2.2.

**Comment by taratorio** [comment]
> I think I have an idea when this can happen in 3.0.15:
> 
> * `eth_getBlockByNumber("latest", ...)` uses `rawdb.ReadForkchoiceHead`  to get the "latest" block
> * so it is always guaranteed to be given a block that is _executed_
> * however, we had incorrect behaviour in `NewPayload` which I fixed in 3.2.2 in [execution: fix incorrect unwinding when validating chain #17105](https://github.com/erigontech/erigon/pull/17105)
> * so if there was a NewPayload request from the CL to verify a side chain, it would incorrectly rollback our stage loop back to the connecting point (however it won't update the ForkChoiceHead because that can only be done by a ForkChoiceUpdate, not by a NewPayload)
> * this will unwind our block txnums index (which matches with your description)
> 
> Do you happen to have your erigon logs around the time when you saw this situation? That will help confirm the theory because we will be able to see that unfold in the logs hopefully.
> 
> Also can you try v3.2.2 and see if you hit this issue there?

We tried to test out this theory in a unit test (e.g. https://github.com/erigontech/erigon/pull/18117), however we found that it is not related because txnums index doesn't get unwound as part of NewPayload, only as part of FCU.

But then after talking with @canepat I remembered that @sudeepdino008 did a fix on 3.2 for an issue that fixed sporadic empty eth_getLogs responses - https://github.com/erigontech/erigon/pull/17270.

@squadgazzz how is your erigon 3.2 instance doing - any sight of this issue with it?

We also discussed with @canepat that might be still a good idea to have a validation for exec-ed block num (e.g. https://github.com/erigontech/erigon/pull/17651) and also a similar check if the block hash is a canonical one. This is pending some thought and review from @canepat

**Comment by squadgazzz** [comment]
Thanks @taratorio 🙏 
I need to double-check. We end up switching to websockets btw, but I am still not 100% sure it mitigated the issue.

**Comment by canepat** [comment]
@squadgazzz I'm closing this since #17651 has been merged. Feel free to reopen if you still see this issue with your erigon 3.2.
